In [45]:
print("""
@Description: Exercises
@Author(s): Stephen CUI
@Time: 2023-04-20 22:37:16
""")


@Description: Exercises
@Author(s): Stephen CUI
@Time: 2023-04-20 22:37:16



In [46]:
import torch

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.

In [47]:
a = torch.rand(2, 2)
a

tensor([[0.0663, 0.9573],
        [0.2447, 0.4588]])

In [48]:
a.unsqueeze(0)

tensor([[[0.0663, 0.9573],
         [0.2447, 0.4588]]])

2. Remove the extra dimension you just added to the previous tensor.

In [49]:
a.squeeze(0)

tensor([[0.0663, 0.9573],
        [0.2447, 0.4588]])

Create a random tensor of shape $5\times 3$ in the interval $[3, 7)$

In [50]:
a = torch.rand(5, 3) * (7- 3) + 3
a

tensor([[3.9834, 5.4747, 6.9323],
        [4.3530, 4.8173, 3.9780],
        [4.9454, 3.4239, 6.8939],
        [6.1719, 4.8564, 4.8410],
        [4.4328, 6.7813, 6.8537]])

4. Create a tensor with values from a normal distribution (mean=0, std=1).

In [51]:
a = torch.randn(3, 3)
a

tensor([[-1.3578, -1.3750, -0.0224],
        [ 0.4004, -0.2538,  0.4788],
        [-0.2033, -0.5660,  1.4409]])

In [52]:
a = torch.rand(3, 3)
a.normal_()

tensor([[-2.4515, -1.1668, -0.8156],
        [-0.9636, -0.9109,  0.9140],
        [-0.1485, -0.7598, -1.6560]])

5. Create a random tensor of size $(3,1)$ and then horizontally stack four copies together.

In [53]:
a = torch.rand(3, 1)
torch.cat([a] * 4, dim=1)

tensor([[0.2266, 0.2266, 0.2266, 0.2266],
        [0.4097, 0.4097, 0.4097, 0.4097],
        [0.8610, 0.8610, 0.8610, 0.8610]])

In [54]:
a.expand(3, 4)

tensor([[0.2266, 0.2266, 0.2266, 0.2266],
        [0.4097, 0.4097, 0.4097, 0.4097],
        [0.8610, 0.8610, 0.8610, 0.8610]])

6. Retrieve the indexes of all the nonzero elements in the tensor `torch.Tensor([1, 1, 1, 0, 1])`.

In [55]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

7. Return the batch matrix-matrix product of two three-dimensional matrices (`a=torch.rand(3,4,5)`, `b=torch.rand(3,5,4)`).

In [56]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)

In [57]:
torch.bmm(a, b)

tensor([[[1.3183, 1.1855, 1.1601, 0.6356],
         [1.1862, 1.1155, 0.9579, 0.9366],
         [1.5893, 2.0542, 1.1877, 1.3921],
         [1.6563, 1.4342, 1.0465, 1.1537]],

        [[1.3862, 1.6275, 1.5878, 1.8040],
         [1.8659, 2.5596, 2.0749, 2.2333],
         [0.8816, 1.1554, 1.1044, 0.9647],
         [0.9916, 1.5688, 1.2590, 1.1746]],

        [[0.2529, 0.5533, 0.3852, 0.3455],
         [1.5493, 1.5610, 1.2825, 1.6094],
         [1.2152, 1.5763, 1.2910, 1.1191],
         [1.6376, 2.1609, 1.6514, 1.4816]]])

8. Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (`a=torch.rand(3,4,5)`, `b=torch.rand(5,4)`).

In [58]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[0.9111, 0.9271, 1.8489, 1.7912],
         [1.2336, 1.3651, 1.9784, 2.0473],
         [1.2628, 1.1518, 1.9393, 1.3922],
         [1.0070, 0.8825, 1.5785, 1.0800]],

        [[1.5800, 1.3336, 2.5369, 1.8119],
         [1.0012, 0.9293, 1.9145, 1.5010],
         [0.9237, 0.8922, 1.3865, 1.3791],
         [0.9797, 1.0844, 1.6411, 1.5089]],

        [[0.8572, 0.6149, 1.6363, 1.1954],
         [0.8898, 0.8943, 1.7075, 1.6443],
         [0.7989, 0.9668, 1.2732, 1.3908],
         [1.0538, 1.0518, 1.5507, 1.3361]]])