In [1]:
print("""
@Description: Pytorch Basics
@Author(s): Stephen CUI
@Time: 2023-04-20 17:36:13
""")


@Description: Pytorch Basics
@Author(s): Stephen CUI
@Time: 2023-04-20 17:36:13



In [2]:
import torch

In [3]:
cnt = 0


def describe(x):
    global cnt
    print('----- {} times output -----'.format(cnt))
    cnt += 1
    print('Type: {}'.format(x.type()))
    print('Shape/Size: {}'.format(x.shape))
    print('Values: \n{}'.format(x))

In [4]:
x = torch.arange(6).view(2, 3)
describe(x)

----- 0 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [5]:
describe(torch.cat([x, x], dim=0))

----- 1 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [6]:
describe(torch.cat([x, x], dim=1))

----- 2 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [7]:
describe(torch.stack([x, x]))

----- 3 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


PyTorch also implements highly efficient linear algebra operations on tensors

In [8]:
x1 = torch.arange(6, dtype=torch.float).view(2, 3)
describe(x1)

----- 4 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [9]:
x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

----- 5 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [10]:
describe(torch.mm(x1, x2))

----- 6 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


### Tensors and Computational Graphs 

In [11]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
x.grad is None

----- 7 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


True

In [12]:
y = (x + 2) * (x + 5) + 3
describe(y)
x.grad is None

----- 8 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)


True

In [13]:
z = y.mean()
describe(z)
z.backward()
x.grad is None

----- 9 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([])
Values: 
21.0


False

### CUDA Tensors

In [14]:
assert torch.cuda.is_available()

In [15]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [16]:
x = torch.rand(3, 3).to(device)
describe(x)

----- 10 times output -----
Type: torch.cuda.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[0.6245, 0.8701, 0.0331],
        [0.2591, 0.5645, 0.0178],
        [0.9705, 0.1941, 0.6954]], device='cuda:0')


In [17]:
y = torch.rand(3, 3)
x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [18]:
cpu_device = torch.device('cpu')
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

tensor([[1.2269, 1.3481, 0.1759],
        [0.4820, 1.0830, 0.1275],
        [1.6901, 0.7489, 0.7392]])