In [1]:
print("""
@Description: Pytorch Basics
@Author(s): Stephen CUI
@Time: 2023-04-20 17:36:13
""")


@Description: Pytorch Basics
@Author(s): Stephen CUI
@Time: 2023-04-20 17:36:13



In [2]:
import torch

In [3]:
cnt = 0


def describe(x):
    global cnt
    print('----- {} times output -----'.format(cnt))
    cnt += 1
    print('Type: {}'.format(x.type()))
    print('Shape/Size: {}'.format(x.shape))
    print('Values: \n{}'.format(x))

In [4]:
x = torch.arange(6).view(2, 3)
describe(x)

----- 0 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [5]:
describe(torch.cat([x, x], dim=0))

----- 1 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [6]:
describe(torch.cat([x, x], dim=1))

----- 2 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [7]:
describe(torch.stack([x, x]))

----- 3 times output -----
Type: torch.LongTensor
Shape/Size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


PyTorch also implements highly efficient linear algebra operations on tensors

In [15]:
x1 = torch.arange(6, dtype=torch.float).view(2, 3)
describe(x1)

----- 9 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [16]:
x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

----- 10 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [17]:
describe(torch.mm(x1, x2))

----- 11 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


### Tensors and Computational Graphs 

In [36]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
x.grad is None

----- 29 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


True

In [37]:
y = (x + 2) * (x + 5) + 3
describe(y)
x.grad is None

----- 30 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)


True

In [38]:
z = y.mean()
describe(z)
z.backward()
x.grad is None

----- 31 times output -----
Type: torch.FloatTensor
Shape/Size: torch.Size([])
Values: 
21.0


False